### ISSUE TITLE
Missing files at compile time

### ISSUE THREAD

**Issue by K-Faktor** [Iswenzz/CoD4-Battleroyale#1]
ERROR: Couldn't find material 'hud_icon_mag_12_gauge'
ERROR: failed loading 'hud_icon_mag_12_gauge' of type 'material'
Sound file 'sound/weapons/unit/wpfoly_uav_control_unit_pullout.wav' not found
Sound file 'sound/weapons/unit/wpfoly_uav_control_unit_putaway.wav' not found
Error: file ui/error.menu, line 9: file ui_mp\surf_common.inc not found
ERROR: Couldn't find material 'bg_theme'
Error: file ui_mp/scriptmenus/sr_welcome.menu, line 15: file ui_mp\dr_common.inc not found

**Comment by ArashGorge** [comment]
not any updates ?
